/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/components/features/Admin/Admin-Layout.vue')['default']
    BaseBadge: typeof import('./src/components/base/BaseBadge.vue')['default']
    BaseBreadcrumb: typeof import('./src/components/base/BaseBreadcrumb.vue')['default']
    BaseButton: typeof import('./src/components/base/BaseButton.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    CommonCard: typeof import('./src/components/common/CommonCard.vue')['default']
    CommonCollapse: typeof import('./src/components/common/CommonCollapse.vue')['default']
    CommonModal: typeof import('./src/components/common/CommonModal.vue')['default']
    CommonTable: typeof import('./src/components/common/CommonTable.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HRLayout: typeof import('./src/components/features/HR/HR-Layout.vue')['default']
    IconArrow: typeof import('./src/components/icons/IconArrow.vue')['default']
    IconBenefit: typeof import('./src/components/icons/IconBenefit.vue')['default']
    IconCandidate: typeof import('./src/components/icons/IconCandidate.vue')['default']
    IconClipboard: typeof import('./src/components/icons/IconClipboard.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconCV: typeof import('./src/components/icons/IconCV.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconDollar: typeof import('./src/components/icons/IconDollar.vue')['default']
    IconDot: typeof import('./src/components/icons/IconDot.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconEmployee: typeof import('./src/components/icons/IconEmployee.vue')['default']
    IconLeave: typeof import('./src/components/icons/IconLeave.vue')['default']
    IconMessage: typeof import('./src/components/icons/IconMessage.vue')['default']
    IconNotification: typeof import('./src/components/icons/IconNotification.vue')['default']
    IconPayroll: typeof import('./src/components/icons/IconPayroll.vue')['default']
    IconRecruitment: typeof import('./src/components/icons/IconRecruitment.vue')['default']
    IconSetting: typeof import('./src/components/icons/IconSetting.vue')['default']
    IconSingleUser: typeof import('./src/components/icons/IconSingleUser.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconTraining: typeof import('./src/components/icons/IconTraining.vue')['default']
    IconTrainning: typeof import('./src/components/icons/IconTrainning.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NDropdownItem: typeof import('naive-ui')['NDropdownItem']
    NDropdownOption: typeof import('naive-ui')['NDropdownOption']
    NIcon: typeof import('naive-ui')['NIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StaffLayout: typeof import('./src/components/features/Staffs/Staff-Layout.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
